---
http_interactions:
- request:
    method: post
    uri: https://development.avalara.net/1.0/tax/get
    body:
      encoding: UTF-8
      string: '{"DocCode":"R824569147","DocDate":"2017-01-10","Discount":"0.0","Commit":false,"DocType":"SalesOrder","Addresses":[{"AddressCode":"Orig","Line1":"915
        S Jackson St","Line2":"","City":"Montgomery","Region":"AL","PostalCode":"36104","Country":"US"},{"AddressCode":"Dest","Line1":"A
        Different Road","Line2":"","City":"Montgomery","Region":"Alabama","Country":"US","PostalCode":"36104"}],"Lines":[{"LineNo":"1-LI","Description":"Product
        #154 - 9475","TaxCode":"PC030000","ItemCode":"SKU-154","Qty":1,"Amount":10.0,"OriginCode":"Orig","DestinationCode":"Dest","CustomerUsageType":null,"Discounted":false,"TaxIncluded":false}],"CustomerCode":1,"CompanyCode":"[Company]","CustomerUsageType":null,"ExemptionNo":null,"Client":"a0o33000004FH8l","ReferenceCode":"R824569147","DetailLevel":"Tax","CurrencyCode":"USD"}'
    headers:
      Accept:
      - "*/*; q=0.5, application/xml"
      Accept-Encoding:
      - gzip, deflate
      Authorization:
      - Basic MTEwMDExMzA5NjoxRDEzRURBMkRDQ0M3RTRB
      Content-Type:
      - application/json
      Content-Length:
      - '800'
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - private
      Content-Type:
      - text/json; charset=utf-8
      Content-Encoding:
      - gzip
      Vary:
      - Accept-Encoding
      X-Aspnet-Version:
      - 4.0.30319
      X-Powered-By:
      - ASP.NET
      Date:
      - Tue, 10 Jan 2017 08:42:37 GMT
      Content-Length:
      - '581'
      Set-Cookie:
      - TS017f1821=01a8ddc44ee765c34a7e2eb4fe854a08cc638bb3668f69cd8fc566af377d2f205edf4e9c2ad74618983cc224facc1274fd2fab4ca7;
        Path=/
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAEAO29B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3m
        kuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZk
        AWz2zkrayZ4hgKrIHz9+fB8/In5x8tGrvFmX7Uk1yz96lH70ej2d5k3z0Sj5
        6Gk1NZ++Otjbv//pw939B/rF06zlL/Z2dh9s7+xu7+7gizfFIm/abLEKv3qz
        c/Bof+/RvQfj+wcHewf3Hv4UN67arDxeVOtli+YKAR8+LZqp+dh9evouX6za
        olqGH7/J3mWTkpHxQNCn+GRnvO9/dJKV03VJqM/8L7N3z4tl3tBH30uIHvjj
        RUV/fbS7/fxMWxhCvDzZubdDj36cTYqyaK/xTVuvc3z6hDCfZfX18/wyL/HF
        TxWr+/iij39/nIDoj+UV4Yq/dsY7+9Qrf0aN5COD/dConuZtVpR2XCfoqmZc
        v3qNJq/yC8Xm+Dn+/s66Lpo31yvu8XVLAO2nZvg7u/iIYL8vmgzlRbbgZsfP
        j58cf3GMz6mV+zR9/eb4zWn65vj3/uiXJN9P8H9pcjyb1cSUbo70A/rzo+P0
        aXF+ntf5sk1fVdkMUPVrg/VTYkp8fKJT9UW1bC+qRU7EwKddurysiIdL8/K9
        T3d3eAhdchFe8tEZ031v5/7eg4cP8Q0P1ry/s7u7s3t/F1T5JckoxP3h7v30
        dfqdbPq2qZbpa0ZSvzavf1kXF/j45x53MxkR0f8lyf8DYJRDHUgEAAA=
    http_version:
  recorded_at: Tue, 10 Jan 2017 08:42:37 GMT
- request:
    method: post
    uri: https://development.avalara.net/1.0/tax/get
    body:
      encoding: UTF-8
      string: '{"DocCode":"R824569147","DocDate":"2017-01-10","Discount":"0.0","Commit":false,"DocType":"SalesOrder","Addresses":[{"AddressCode":"Orig","Line1":"915
        S Jackson St","Line2":"","City":"Montgomery","Region":"AL","PostalCode":"36104","Country":"US"},{"AddressCode":"Dest","Line1":"A
        Different Road","Line2":"","City":"Montgomery","Region":"Alabama","Country":"US","PostalCode":"36104"},{"AddressCode":"2","Line1":"1600
        Pennsylvania Ave NW","Line2":null,"City":"Washington","PostalCode":"20500","Country":"US"}],"Lines":[{"LineNo":"1-LI","Description":"Product
        #154 - 9475","TaxCode":"PC030000","ItemCode":"SKU-154","Qty":1,"Amount":10.0,"OriginCode":"2","DestinationCode":"Dest","CustomerUsageType":null,"Discounted":false,"TaxIncluded":false},{"LineNo":"1-FR","ItemCode":"Avalara
        Ground","Qty":1,"Amount":5.0,"OriginCode":"2","DestinationCode":"Dest","CustomerUsageType":null,"Description":"Shipping
        Charge","TaxCode":"FR000000","Discounted":false,"TaxIncluded":false}],"CustomerCode":1,"CompanyCode":"[Company]","CustomerUsageType":null,"ExemptionNo":null,"Client":"a0o33000004FH8l","ReferenceCode":"R824569147","DetailLevel":"Tax","CurrencyCode":"USD"}'
    headers:
      Accept:
      - "*/*; q=0.5, application/xml"
      Accept-Encoding:
      - gzip, deflate
      Authorization:
      - Basic MTEwMDExMzA5NjoxRDEzRURBMkRDQ0M3RTRB
      Content-Type:
      - application/json
      Content-Length:
      - '1147'
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - private
      Content-Type:
      - text/json; charset=utf-8
      Content-Encoding:
      - gzip
      Vary:
      - Accept-Encoding
      X-Aspnet-Version:
      - 4.0.30319
      X-Powered-By:
      - ASP.NET
      Date:
      - Tue, 10 Jan 2017 08:42:39 GMT
      Content-Length:
      - '673'
      Set-Cookie:
      - TS017f1821=01a8ddc44e2c22f96e67fd53a043c2cbdc229dfbc6d7918c53353fab6e83ef6564bd34b4d6e08be32a6208ce010f1d23a2a6f088ed;
        Path=/
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAEAO29B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3m
        kuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZk
        AWz2zkrayZ4hgKrIHz9+fB8/In5x8tGrvFmX7Uk1yz96lH70ej2d5k3z0Sj5
        6Gk1NZ++Otjbv//pw939B/rF06zlL/Z2dh9s7+xu7+7gizfFIm/abLEKv3qz
        c/Bof+/RvYPxw4e7e3sP9n+KG1dtVh4vqvWyRfPd+/bDp0UzNR8LXHx6+i5f
        rNqiWoYfv8neZZOSkfFA0Kf4ZGf8qf/RSVZO1yWhPvO/zN49L5Z5Qx99LyF6
        4I8XFf310e728zNtYQjx8mTn3g49+nE2KcqivcY3bb3O8ekTwnyW1dfP88u8
        xBc/VawYrz7+/XECoo6FP3hFuOKvnfHOPvXKn1Ej+Whf/+qOynz+NG+zorTj
        OkFXNeP61Ws0eZVfKDbHz/H3d9Z10by5XnGPr1sCaD81w9/ZxUcE+33RZCgv
        sgU3O35+/OT4i2N8Tq3cp+nrN8dvTtM3x7/3R78k+X7yS5IRoe1Px7NX+o7B
        59kr6o0e/fhnbzr4lY3D3NO/urNhPv9hzMYtsWQgjuy3nIzvJ9LkeDarSUM4
        gdEP6M+PjtOnxfl5XufLNn1VZTNA1a8N0k9JQ+DjE52oL6ple1EtcqIFPu2S
        5WVFCqU0L9/7dHeH+alLLcJLPjpjsu/t3N978PAhvuHBmvd3dnd3du/vgirC
        XYocvtv9dGcnfZkvl811eZktiyw9vszTF98FEG1mwDAVzQC+mzXzYnnREjr4
        dPMACDHqmz4WbPHR0xP83RkAtwlQJ8z1IdTNXETU8C9J/h+0pa4g1AUAAA==
    http_version:
  recorded_at: Tue, 10 Jan 2017 08:42:38 GMT
- request:
    method: post
    uri: https://development.avalara.net/1.0/tax/get
    body:
      encoding: UTF-8
      string: '{"DocCode":"R824569147","DocDate":"2017-01-10","Discount":"0.0","Commit":false,"DocType":"SalesOrder","Addresses":[{"AddressCode":"Orig","Line1":"915
        S Jackson St","Line2":"","City":"Montgomery","Region":"AL","PostalCode":"36104","Country":"US"},{"AddressCode":"Dest","Line1":"A
        Different Road","Line2":"","City":"Montgomery","Region":"Alabama","Country":"US","PostalCode":"36104"},{"AddressCode":"2","Line1":"1600
        Pennsylvania Ave NW","Line2":null,"City":"Washington","PostalCode":"20500","Country":"US"}],"Lines":[{"LineNo":"1-LI","Description":"Product
        #154 - 9475","TaxCode":"PC030000","ItemCode":"SKU-154","Qty":1,"Amount":10.0,"OriginCode":"2","DestinationCode":"Dest","CustomerUsageType":null,"Discounted":false,"TaxIncluded":false},{"LineNo":"1-FR","ItemCode":"Avalara
        Ground","Qty":1,"Amount":5.0,"OriginCode":"2","DestinationCode":"Dest","CustomerUsageType":null,"Description":"Shipping
        Charge","TaxCode":"FR000000","Discounted":false,"TaxIncluded":false}],"CustomerCode":1,"CompanyCode":"[Company]","CustomerUsageType":null,"ExemptionNo":null,"Client":"a0o33000004FH8l","ReferenceCode":"R824569147","DetailLevel":"Tax","CurrencyCode":"USD"}'
    headers:
      Accept:
      - "*/*; q=0.5, application/xml"
      Accept-Encoding:
      - gzip, deflate
      Authorization:
      - Basic MTEwMDExMzA5NjoxRDEzRURBMkRDQ0M3RTRB
      Content-Type:
      - application/json
      Content-Length:
      - '1147'
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - private
      Content-Type:
      - text/json; charset=utf-8
      Content-Encoding:
      - gzip
      Vary:
      - Accept-Encoding
      X-Aspnet-Version:
      - 4.0.30319
      X-Powered-By:
      - ASP.NET
      Date:
      - Tue, 10 Jan 2017 08:42:40 GMT
      Content-Length:
      - '672'
      Set-Cookie:
      - TS017f1821=01a8ddc44eec26b3e90454b78560af56e0344e8cffb57f7b6f5ef91ae84a9c1b7d8024e92470b90e88220be94b6fc64b9064d8e39d;
        Path=/
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAEAO29B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3m
        kuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZk
        AWz2zkrayZ4hgKrIHz9+fB8/In5x8tGrvFmX7Uk1yz96lH70ej2d5k3z0Sj5
        6Gk1NZ++Otjbv//pw939B/rF06zlL/Z2dh9s7+xu7+7gizfFIm/abLEKv3qz
        c/Bof+/R/s7404efPnyw8/CnuHHVZuXxolovWzTfvW8/fFo0U/OxwMWnp+/y
        xaotqmX48ZvsXTYpGRkPBH2KT6hH/6OTrJyuS0J95n+ZvXteLPOGPvpeQvTA
        Hy8q+uuj3e3nZ9rCEOLlyc69HXr042xSlEV7jW/aep3j0yeE+Syrr5/nl3mJ
        L36qWDFeffz74wREHQt/8IpwxV8745196pU/o0by0b7+1R2V+fxp3mZFacd1
        gq5qxvWr12jyKr9QbI6f4+/vrOuieXO94h5ftwTQfmqGv7OLjwj2+6LJUF5k
        C252/Pz4yfEXx/icWrlP09dvjt+cpm+Of++Pfkny/eSXJCNC25+OZ6/0HYPP
        s1fUGz368c/edPArG4e5p391Z8N8/sOYjVtiyUAc2W85Gd9PpMnxbFaThnAC
        ox/Qnx8dp0+L8/O8zpdt+qrKZoCqXxukn5KGwMcnOlFfVMv2olrkRAt82iXL
        y4oUSmlevvfp7g7zU5dahJd8dMZk39u5v/fg4UN8w4M17+/s7u7s3t8FVYS7
        FDl8t/vpzk76Ml8um+vyMlsWWXp8macvvgsg2syAYSqaAXw3a+bF8qIldPDp
        5gEQYtQ3fSzY4qOnJ/i7MwBuE6BOmOtDqJu5iKjhX5L8P11lnVzUBQAA
    http_version:
  recorded_at: Tue, 10 Jan 2017 08:42:40 GMT
recorded_with: VCR 3.0.3
